config/routes.rb
Rails.application.routes.draw do
  resources :jobs do
    post 'comments' => 'comments#create'
  end

  delete "comments/:id" => "comments#destroy", as: :comment
  
  root "jobs#premium"# rails 4
  #root to: 'jobs#index' # rails 3

  get 'hello/world' => 'hello#world'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :job
    validates :name, :body, :job_id, presence: true
end

app/models/job.rb
class Job < ApplicationRecord
    has_many :comments
    scope :mais_recente, -> {order("created_at DESC")}
    validates :title, :description, presence: true #rails 5
    #validates_presence_of :title, :description #rails 3
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def comment_params
        return params.require(:comment).permit(:name, :body)
    end

    def create
        @job = Job.find(params[:job_id])
        @comment = @job.comments.build(comment_params)
        if @comment.save
            flash[:notice] = "Comentário adicionado com sucesso!"
        else
            flash[:alert] = "Preencha todos os campos!"
        end
        redirect_to @job
    end   
    
    def destroy
        @comment = Comment.find(params[:id])
        @comment.destroy
        #flash[:notice] = "Comment destroyed with sucess!"   
        #redirect_to @comment.job
        redirect_to @comment.job, notice: "Comment destroyed with success."
    end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def world
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.mais_recente.paginate(page: params[:page], per_page: 5)
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def premium
    @jobs = Job.where(premium: true).mais_recente.paginate(page: params[:page], per_page: 5)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :premium)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
   def job_title (job)
    title = h(job.title)
    if job.premium
        title + content_tag(:strong, " (premium)")
    else
        title
    end           
   end
end

app/views/comments/_comment.html.erb
<h3><%= comment.name %> said:</h3>
<%= comment.body%>
(Sent <strong><%= time_ago_in_words comment.created_at%> </strong>ago) 
<%= link_to "Destroy", comment_path(comment), method: :delete, data: {confirm: "Are you sure?"} %>
<br><br>

app/views/comments/_form.html.erb
<%= form_for [@job , Comment.new] do |f| %>
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, class:"form-control" %>
    </div>
    <div class="field">
        <%= f.label :body %>
        <%= f.text_area :body, class:"form-control", rows:4 %>
    </div> 
    <div class = "actions">
        <%= f.button class:"btn btn-default" do %>
        Send <i class="glyphicon glyphicon-ok"></i> 
        <%end%>
    </div>   
<% end %>

app/views/hello/world.html.erb
<h1>Hello#world</h1>
<strong><%= Time.now %></strong><br>

<%= link_to 'Jobs', root_path %>

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" >
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>      
        <li><%= message %></li>        
      <% end %>
      </ul>
      
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :premium %>
    <%= form.check_box :premium %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class:"form-control", rows:3 %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-default" %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<h3><%= job_title(job) %></h3>  

<%= job.description %>
<p>
  <%= pluralize(job.comments.size, "comment")%>
  <%= link_to 'Show', job %> |
  <%= link_to 'Edit', edit_job_path(job) %> |
  <%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>
<br>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Jobs</h1><br><br>
<%= render @jobs %>
<%= will_paginate @jobs %>
<br>
<%= link_to 'New Job', new_job_path %><br><br>
<%= link_to 'Premium Jobs', root_path %><br><br>
<%= link_to 'Hello World', hello_world_path %><br><br>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/premium.html.erb
<p id="notice"><%= notice %></p>

<h1>Premium Jobs</h1>

<%= render @jobs%>
<%= will_paginate @jobs %>
<br><br><br>
<%= link_to 'New Job', new_job_path %><br><br>
<%= link_to 'All Jobs', jobs_path %><br><br>
<%= link_to 'Hello World', hello_world_path %><br><br>

app/views/jobs/show.html.erb
<p id="notice" class="bg-success"><%= notice %></p>
<p id="alert" class="bg-danger"><%= alert %></p>

   <h2><%= job_title(@job)%></h2>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<%= pluralize(@job.comments.size, "comment")%>
<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

<h2> Send a new Comment </h2>
<%= render "comments/form"%>

<%= render @job.comments%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobsCard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>